name: CI

on:
  push:
    branches: ['*']  # Trigger on push to any branch
  pull_request:
    branches: [ main ]  # Trigger on PRs to main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'  # Or adopt, zulu, etc.
        java-version: '17'       # Set your project's Java version

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build and run tests
      run: mvn clean verify  # This runs unit and integration tests

    - name: Upload test reports
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-reports
        path: target/surefire-reports/  # Adjust if you're using a different directory

