name: Java Maven CI/CD

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

  # CD trigger — when code is pushed to main
  workflow_dispatch:  # Allows manual trigger from GitHub UI
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and test with Maven
        working-directory: AI_Personalised_Learning_Project
        run: mvn clean verify

  release-artifact:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build JAR
        working-directory: AI_Personalised_Learning_Project
        run: mvn clean package

      - name: Upload Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ai-learning-app
          path: AI_Personalised_Learning_Project/target/*.jar
